//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsData
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://example.org/", ConfigurationName="FlightsData.FlightService")]
    public interface FlightService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example.org/FlightService/getAllFlightsRequest", ReplyAction="http://example.org/FlightService/getAllFlightsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FlightsData.getAllFlightsResponse> getAllFlightsAsync(FlightsData.getAllFlightsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example.org/FlightService/searchFlightsRequest", ReplyAction="http://example.org/FlightService/searchFlightsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FlightsData.searchFlightsResponse> searchFlightsAsync(FlightsData.searchFlightsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example.org/FlightService/getFlightByNumberRequest", ReplyAction="http://example.org/FlightService/getFlightByNumberResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FlightsData.getFlightByNumberResponse> getFlightByNumberAsync(FlightsData.getFlightByNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example.org/FlightService/getUserTicketsRequest", ReplyAction="http://example.org/FlightService/getUserTicketsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FlightsData.getUserTicketsResponse> getUserTicketsAsync(FlightsData.getUserTicketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example.org/FlightService/purchaseTicketRequest", ReplyAction="http://example.org/FlightService/purchaseTicketResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FlightsData.purchaseTicketResponse> purchaseTicketAsync(FlightsData.purchaseTicketRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://example.org/")]
    public partial class flight
    {
        
        private string flightNumberField;
        
        private string cityFromField;
        
        private string cityToField;
        
        private string dayField;
        
        private string timeField;
        
        private bool visibleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string flightNumber
        {
            get
            {
                return this.flightNumberField;
            }
            set
            {
                this.flightNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cityFrom
        {
            get
            {
                return this.cityFromField;
            }
            set
            {
                this.cityFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cityTo
        {
            get
            {
                return this.cityToField;
            }
            set
            {
                this.cityToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string day
        {
            get
            {
                return this.dayField;
            }
            set
            {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool visible
        {
            get
            {
                return this.visibleField;
            }
            set
            {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://example.org/")]
    public partial class ticket
    {
        
        private flight flightDetailsField;
        
        private string passengerEmailField;
        
        private string passengerNameField;
        
        private string passengerPhoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public flight flightDetails
        {
            get
            {
                return this.flightDetailsField;
            }
            set
            {
                this.flightDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string passengerEmail
        {
            get
            {
                return this.passengerEmailField;
            }
            set
            {
                this.passengerEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string passengerName
        {
            get
            {
                return this.passengerNameField;
            }
            set
            {
                this.passengerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string passengerPhone
        {
            get
            {
                return this.passengerPhoneField;
            }
            set
            {
                this.passengerPhoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllFlights", WrapperNamespace="http://example.org/", IsWrapped=true)]
    public partial class getAllFlightsRequest
    {
        
        public getAllFlightsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllFlightsResponse", WrapperNamespace="http://example.org/", IsWrapped=true)]
    public partial class getAllFlightsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FlightsData.flight[] @return;
        
        public getAllFlightsResponse()
        {
        }
        
        public getAllFlightsResponse(FlightsData.flight[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchFlights", WrapperNamespace="http://example.org/", IsWrapped=true)]
    public partial class searchFlightsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public searchFlightsRequest()
        {
        }
        
        public searchFlightsRequest(string arg0, string arg1, string arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchFlightsResponse", WrapperNamespace="http://example.org/", IsWrapped=true)]
    public partial class searchFlightsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FlightsData.flight[] @return;
        
        public searchFlightsResponse()
        {
        }
        
        public searchFlightsResponse(FlightsData.flight[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFlightByNumber", WrapperNamespace="http://example.org/", IsWrapped=true)]
    public partial class getFlightByNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getFlightByNumberRequest()
        {
        }
        
        public getFlightByNumberRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFlightByNumberResponse", WrapperNamespace="http://example.org/", IsWrapped=true)]
    public partial class getFlightByNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FlightsData.flight @return;
        
        public getFlightByNumberResponse()
        {
        }
        
        public getFlightByNumberResponse(FlightsData.flight @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserTickets", WrapperNamespace="http://example.org/", IsWrapped=true)]
    public partial class getUserTicketsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getUserTicketsRequest()
        {
        }
        
        public getUserTicketsRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserTicketsResponse", WrapperNamespace="http://example.org/", IsWrapped=true)]
    public partial class getUserTicketsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FlightsData.ticket[] @return;
        
        public getUserTicketsResponse()
        {
        }
        
        public getUserTicketsResponse(FlightsData.ticket[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="purchaseTicket", WrapperNamespace="http://example.org/", IsWrapped=true)]
    public partial class purchaseTicketRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        public purchaseTicketRequest()
        {
        }
        
        public purchaseTicketRequest(string arg0, string arg1, string arg2, string arg3)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="purchaseTicketResponse", WrapperNamespace="http://example.org/", IsWrapped=true)]
    public partial class purchaseTicketResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FlightsData.ticket @return;
        
        public purchaseTicketResponse()
        {
        }
        
        public purchaseTicketResponse(FlightsData.ticket @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface FlightServiceChannel : FlightsData.FlightService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class FlightServiceClient : System.ServiceModel.ClientBase<FlightsData.FlightService>, FlightsData.FlightService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FlightServiceClient() : 
                base(FlightServiceClient.GetDefaultBinding(), FlightServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.FlightServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FlightServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(FlightServiceClient.GetBindingForEndpoint(endpointConfiguration), FlightServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FlightServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FlightServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FlightServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FlightServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FlightServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlightsData.getAllFlightsResponse> FlightsData.FlightService.getAllFlightsAsync(FlightsData.getAllFlightsRequest request)
        {
            return base.Channel.getAllFlightsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlightsData.getAllFlightsResponse> getAllFlightsAsync()
        {
            FlightsData.getAllFlightsRequest inValue = new FlightsData.getAllFlightsRequest();
            return ((FlightsData.FlightService)(this)).getAllFlightsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlightsData.searchFlightsResponse> FlightsData.FlightService.searchFlightsAsync(FlightsData.searchFlightsRequest request)
        {
            return base.Channel.searchFlightsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlightsData.searchFlightsResponse> searchFlightsAsync(string arg0, string arg1, string arg2)
        {
            FlightsData.searchFlightsRequest inValue = new FlightsData.searchFlightsRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((FlightsData.FlightService)(this)).searchFlightsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlightsData.getFlightByNumberResponse> FlightsData.FlightService.getFlightByNumberAsync(FlightsData.getFlightByNumberRequest request)
        {
            return base.Channel.getFlightByNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlightsData.getFlightByNumberResponse> getFlightByNumberAsync(string arg0)
        {
            FlightsData.getFlightByNumberRequest inValue = new FlightsData.getFlightByNumberRequest();
            inValue.arg0 = arg0;
            return ((FlightsData.FlightService)(this)).getFlightByNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlightsData.getUserTicketsResponse> FlightsData.FlightService.getUserTicketsAsync(FlightsData.getUserTicketsRequest request)
        {
            return base.Channel.getUserTicketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlightsData.getUserTicketsResponse> getUserTicketsAsync(string arg0)
        {
            FlightsData.getUserTicketsRequest inValue = new FlightsData.getUserTicketsRequest();
            inValue.arg0 = arg0;
            return ((FlightsData.FlightService)(this)).getUserTicketsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlightsData.purchaseTicketResponse> FlightsData.FlightService.purchaseTicketAsync(FlightsData.purchaseTicketRequest request)
        {
            return base.Channel.purchaseTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlightsData.purchaseTicketResponse> purchaseTicketAsync(string arg0, string arg1, string arg2, string arg3)
        {
            FlightsData.purchaseTicketRequest inValue = new FlightsData.purchaseTicketRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((FlightsData.FlightService)(this)).purchaseTicketAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FlightServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FlightServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9999/ws/flights");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FlightServiceClient.GetBindingForEndpoint(EndpointConfiguration.FlightServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FlightServiceClient.GetEndpointAddress(EndpointConfiguration.FlightServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            FlightServiceImplPort,
        }
    }
}
